"use client";

import { useState, useCallback } from "react";
import { Send, Clock, Sparkles } from "lucide-react";
import extraData from "@/data/extraQuestions.json";
import type { Question } from "@/types";
import Timer from "@/components/Timer";
import ResultsView from "@/components/ResultsView";

const extraQuestions: Question[] = extraData as Question[];

function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

type Phase = "setup" | "quiz" | "results";

export default function PracticePage() {
  const [phase, setPhase] = useState<Phase>("setup");
  const [timerEnabled, setTimerEnabled] = useState(false);
  const [quizQuestions, setQuizQuestions] = useState<Question[]>([]);
  const [selectedAnswers, setSelectedAnswers] = useState<
    Record<string, string>
  >({});
  const [elapsed, setElapsed] = useState(0);
  const [isTimerRunning, setIsTimerRunning] = useState(false);

  const start = () => {
    setQuizQuestions(shuffleArray(extraQuestions));
    setSelectedAnswers({});
    setElapsed(0);
    setIsTimerRunning(timerEnabled);
    setPhase("quiz");
    window.scrollTo({ top: 0 });
  };

  const handleTick = useCallback(() => setElapsed((t) => t + 1), []);

  const handleSubmit = () => {
    setIsTimerRunning(false);
    setPhase("results");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleReset = () => {
    setPhase("setup");
    setQuizQuestions([]);
    setSelectedAnswers({});
    setElapsed(0);
    setIsTimerRunning(false);
    window.scrollTo({ top: 0 });
  };

  const answeredCount = Object.keys(selectedAnswers).length;
  const total = quizQuestions.length;

  // ── SETUP ──
  if (phase === "setup") {
    return (
      <div className="max-w-xl mx-auto px-4 sm:px-6 py-10">
        <div className="mb-8">
          <h1 className="text-xl font-semibold text-white mb-1">
            Extra Practice
          </h1>
          <p className="text-sm text-[#71717a]">
            20 additional questions for deeper review.
          </p>
        </div>

        <div className="border border-[#1f1f1f] rounded-xl p-4 mb-5">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-3.5 h-3.5 text-[#71717a]" />
            <span className="text-xs font-medium text-[#a1a1aa]">
              AI Generated
            </span>
          </div>
          <p className="text-xs text-[#71717a] leading-relaxed">
            These questions were generated by AI to supplement the official
            content. Good for concept review.
          </p>
        </div>

        <div className="flex items-center justify-between p-4 rounded-xl border border-[#1f1f1f] mb-6">
          <div className="flex items-center gap-2">
            <Clock className="w-3.5 h-3.5 text-[#71717a]" />
            <span className="text-sm text-[#a1a1aa]">Track time</span>
          </div>
          <button
            onClick={() => setTimerEnabled(!timerEnabled)}
            className={`relative w-9 h-5 rounded-full transition-colors ${timerEnabled ? "bg-[#22c55e]" : "bg-[#1f1f1f]"}`}
          >
            <span
              className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform ${timerEnabled ? "translate-x-4" : "translate-x-0"}`}
            />
          </button>
        </div>

        <button
          onClick={start}
          className="w-full py-3 rounded-xl border border-[#3f3f46] text-white font-semibold text-sm hover:border-white hover:bg-white/5 transition-all"
        >
          Start Practice
        </button>
      </div>
    );
  }

  // ── RESULTS ──
  if (phase === "results") {
    return (
      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-10">
        <ResultsView
          questions={quizQuestions}
          selectedAnswers={selectedAnswers}
          onRetry={handleReset}
          title="Practice Results"
          elapsed={timerEnabled ? elapsed : undefined}
        />
      </div>
    );
  }

  // ── QUIZ (long scroll) ──
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-8 pb-28">
      {/* Sticky top bar */}
      <div className="sticky top-14 z-40 bg-[#0a0a0a]/95 backdrop-blur-md border-b border-[#1f1f1f] pb-3 mb-8 pt-3">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <Sparkles className="w-3 h-3 text-[#71717a]" />
            <p className="text-xs text-[#71717a]">
              {answeredCount}/{total} answered · AI Generated
            </p>
          </div>
          {timerEnabled && (
            <Timer
              elapsed={elapsed}
              isRunning={isTimerRunning}
              onTick={handleTick}
            />
          )}
        </div>
        <div className="h-px bg-[#1f1f1f] rounded-full overflow-hidden">
          <div
            className="h-full bg-white rounded-full transition-all duration-300"
            style={{
              width: `${total > 0 ? (answeredCount / total) * 100 : 0}%`,
            }}
          />
        </div>
      </div>

      {/* Questions */}
      <div className="space-y-4">
        {quizQuestions.map((question, i) => {
          const selected = selectedAnswers[question.id];
          return (
            <div
              key={question.id}
              className="border border-[#1f1f1f] rounded-xl p-5"
            >
              <div className="flex gap-3 mb-2">
                <span className="shrink-0 text-xs font-semibold text-[#71717a] w-6 pt-0.5">
                  {i + 1}.
                </span>
                <div className="flex-1">
                  <p className="text-white text-sm leading-relaxed mb-2">
                    {question.question}
                  </p>
                  <span className="inline-flex items-center gap-1 text-[10px] text-[#71717a] border border-[#1f1f1f] px-1.5 py-0.5 rounded">
                    <Sparkles className="w-2.5 h-2.5" /> AI Generated
                  </span>
                </div>
              </div>
              <div className="space-y-2 pl-9 mt-3">
                {question.options.map((option, oi) => {
                  const isSelected = option === selected;
                  return (
                    <button
                      key={oi}
                      onClick={() =>
                        setSelectedAnswers((prev) => ({
                          ...prev,
                          [question.id]: option,
                        }))
                      }
                      className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-lg border text-xs text-left transition-all cursor-pointer ${
                        isSelected
                          ? "border-white/30 bg-white/5 text-white"
                          : "border-[#1f1f1f] text-[#a1a1aa] hover:border-[#3f3f46] hover:text-white"
                      }`}
                    >
                      <span className="shrink-0 w-4 h-4 rounded flex items-center justify-center text-[10px] font-bold text-[#3f3f46]">
                        {["A", "B", "C", "D"][oi]}
                      </span>
                      <span>{option}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {/* Fixed bottom submit bar */}
      <div className="fixed bottom-0 left-0 right-0 z-50 bg-[#0a0a0a]/95 backdrop-blur-md border-t border-[#1f1f1f]">
        <div className="max-w-2xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-4">
          <div>
            <p className="text-xs text-[#71717a]">
              {answeredCount} of {total} answered
            </p>
            {answeredCount < total && (
              <p className="text-[11px] text-[#71717a]">
                {total - answeredCount} remaining
              </p>
            )}
          </div>
          <button
            onClick={handleSubmit}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl border border-[#3f3f46] text-white font-semibold text-sm hover:border-white hover:bg-white/5 transition-all shrink-0"
          >
            <Send className="w-3.5 h-3.5" />
            Submit
          </button>
        </div>
      </div>
    </div>
  );
}
